services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console UI port
    volumes:
      - minio_data:/data
volumes:
  minio_data:
